webdriver:
  '/Users/SoChigusa/works/Attendance-Management/driver/chromedriver'

json:
  ''

URL:
  'https://docs.google.com/forms/d/e/1FAIpQLSdJelnqnhninHvi4U2tw1BpDdjYi7yAQnRH_UPqhNt7inX8JQ/viewform?usp=sf_link'

spreadsheet-key:
  '1Z0ks-Bo9pe_lJGla17NQgUz3y8Om_PpK9Dictinu_jA'
